# Generated by Django 5.0.6 on 2024-06-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dicom_files/')),
                ('patient_id', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('study_description', models.CharField(max_length=255)),
                ('study_date', models.DateField()),
                ('modalities_in_study', models.CharField(max_length=255)),
                ('accession_number', models.CharField(max_length=50)),
                ('number_of_series', models.IntegerField()),
            ],
        ),
    ]
