# Generated by Django 5.0.6 on 2024-06-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0002_study_rename_modalities_in_study_dicomimage_modality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicomimage',
            old_name='time',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='accession_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='number_of_series',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='body_part',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='file',
            field=models.FileField(upload_to='dicom_images/'),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='modality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
