# Generated by Django 5.0.6 on 2024-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0003_rename_time_dicomimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomimage',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='additional_docs/'),
        ),
        migrations.AddField(
            model_name='study',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='body_part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='modality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='patient_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='procedure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
