# Generated by Django 5.0.6 on 2024-06-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0004_dicomimage_additional_documents_study_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='additional_documents/')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='dicom.study')),
            ],
        ),
    ]
