# Generated by Django 5.0.6 on 2024-06-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0007_dicomimage_dicom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_date',
            field=models.DateField(null=True),
        ),
    ]
