# Generated by Django 5.0.6 on 2024-07-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0008_alter_study_study_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dicom.study')),
            ],
        ),
    ]
