# Generated by Django 5.0.6 on 2024-07-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0009_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
