# Generated by Django 5.0.6 on 2024-07-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0010_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='patient_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
