# Generated by Django 5.0.6 on 2024-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0011_alter_study_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
